### ISSUE TITLE
Error: ENOENT: no such file or directory, uv_os_get_passwd

### ISSUE THREAD

**Issue by MichaelHedman** [stepankuzmin/tilelive-postgis#10]
When I run my app in our Openshift environment I get the following error:

Error: ENOENT: no such file or directory, uv_os_get_passwd

The whole stack trace looks like this:

/opt/app-root/src/node_modules/tilelive-postgis/src/parse.js:5
--
  | const { username } = os.userInfo();
  | ^
  | Error: ENOENT: no such file or directory, uv_os_get_passwd
  | at Error (native)
  | at Object.<anonymous> (/opt/app-root/src/node_modules/tilelive-postgis/src/parse.js:5:25)
  | at Module._compile (module.js:570:32)
  | at Object.Module._extensions..js (module.js:579:10)
  | at Module.load (module.js:487:32)
  | at tryModuleLoad (module.js:446:12)
  | at Function.Module._load (module.js:438:3)
  | at Module.require (module.js:497:17)
  | at require (internal/module.js:20:19)
  | at Object.<anonymous> (/opt/app-root/src/node_modules/tilelive-postgis/src/index.js:2:15)

The call to os.userInfo() should be surrounded by a try-catch to prevent the application from crashing when running the app as a user with no entry in /etc/passwd. See https://github.com/Unitech/pm2/issues/3184 for a similar case.

**Comment by stepankuzmin** [comment]
Thanks for the feedback! Fixed in `v1.3.1`.
