### ISSUE TITLE
Upgrade mapnik version to 3.6.3

### ISSUE THREAD

**Issue by MichaelHedman** [stepankuzmin/tilelive-postgis#11]
I ran into problems running node-mapnik (3.6.2) on our platform because of https://github.com/mapnik/node-mapnik/issues/835.

This was fixed by https://github.com/mapnik/node-mapnik/pull/839 and is included in the planned new milestone version 3.6.3 (https://github.com/mapnik/node-mapnik/milestone/39).

I thought that you would be interested in this, since tilelive-postgis has a 3.6.2 dependency.

**Comment by stepankuzmin** [comment]
Wow, thanks @MichaelHedman! I'll upgrade mapnik to 3.6.3 since it will be released.

**Comment by stepankuzmin** [comment]
I've just released `tilelive-postgis` v1.3.2 with `mapnik` v3.7.1

**Comment by MichaelHedman** [comment]
Cool! I will test this as soon as possible.
