### ISSUE TITLE
Graceful shutdown explanation

### ISSUE THREAD

**Issue by charandas** [stepankuzmin/tilelive-postgis#5]
I looked at the prototype of this implementation, and it has a `close` function to clean up the DB connection.

When looking at tilelive source code, I could not see `close` being invoked unless for the `tillelive.copy` function.

I am using `tilelive.load` only, and am curious how a SIGTERM in my process is currently handled? Alluding to [this](https://blog.risingstack.com/graceful-shutdown-node-js-kubernetes/), could you shed some light on whether the db connection is properly closed before exit?

Thanks.

**Comment by stepankuzmin** [comment]
Hi @charandas! If you want to properly close db connection you need to invoke `close` on `source` object obtained by `tilelive.load`. You can see [here](https://github.com/stepankuzmin/tilelive-postgis/blob/master/test/index.js#L64) how to close connection.

**Comment by charandas** [comment]
Perfect.
