### ISSUE TITLE
Could we support a layerName

### ISSUE THREAD

**Issue by charandas** [stepankuzmin/tilelive-postgis#7]
Currently, the layerName defaults to tableName [here](https://github.com/stepankuzmin/tilelive-postgis/blob/fc853ab4b6a4a59b960dee535fed23406d25c196/src/index.js#L18).

Would it make sense to not expose the backend concern of what the table name in DB is, to the frontend consumers using mapbox-gl, if so I can send a PR.  

Thanks.

**Comment by stepankuzmin** [comment]
Thanks for the issue, @charandas! I think it makes sense, PRs are welcome!

**Comment by charandas** [comment]
PR coming!
